version: '3.9'

services:
    mod_redis:
        image: redis
        volumes:
            - ./mod_redis:/data
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_manager:
        image: aivpn_mod_manager:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
    mod_comm_recv:
        image: aivpn_mod_comm_recv:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
            - ./config:/code/config/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
    mod_comm_send:
        image: aivpn_mod_comm_send:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
    mod_report:
        image: aivpn_mod_report:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
    mod_slips:
        image: aivpn_mod_slips:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
    mod_openvpn:
        privileged: true
        image: aivpn_mod_openvpn:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./data/conf:/etc/openvpn
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        ports:
          - "1194:1194/udp"
        depends_on:
            - mod_redis
            - mod_manager
volumes:
    mod_manager:
    mod_report:
    mod_slips:
    mod_openvpn:
    mod_redis:
    mod_comm_send:
    mod_comm_recv:
