version: '3.9'

services:
    mod_redis:
        image: redis
        volumes:
            - ./mod_redis:/data
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            network: {}
    mod_manager:
        image: aivpn_mod_manager:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
    mod_comm_recv:
        image: aivpn_mod_comm_recv:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
    mod_comm_send:
        image: aivpn_mod_comm_send:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
    mod_report:
        image: aivpn_mod_report:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
    mod_traffic_capture:
        image: aivpn_mod_traffic_capture:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
            - ./mod_traffic_capture:/data/
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            hostnet: {}
    mod_slips:
        image: alpine
        volumes:
            - ./mod_slips:/opt/dataset
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
    mod_openvpn:
        image: alpine
        volumes:
            - ./mod_openvpn:/opt/openvpn
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
        networks:
            network: {}
volumes:
    mod_manager:
    mod_report:
    mod_slips:
    mod_openvpn:
    mod_redis:
    mod_comm_send:
    mod_comm_recv:

networks:
    network:
        driver: overlay
    hostnet:
        external: true
        name: host
