version: '3.1'

services:
    mod_manager:
        image: aivpn_mod_manager:latest
        volumes:
            - ./mod_manager:/opt/manager
        deploy:
            restart_policy:
                condition: on-failure
    mod_comm_recv:
        image: aivpn_mod_comm_recv:latest
        deploy:
            restart_policy:
                condition: on-failure
    mod_comm_send:
        image: aivpn_mod_comm_send:latest
        volumes:
            - ./mod_comm_send:/opt/mod_comm_send
        deploy:
            restart_policy:
                condition: on-failure
    mod_report:
        image: aivpn_mod_report:latest
        volumes:
            - ./mod_report:/opt/report
        deploy:
            restart_policy:
                condition: on-failure
    mod_slips:
        image: alpine
        volumes:
            - ./mod_slips:/opt/dataset
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_redis:
        image: redis
        volumes:
            - ./mod_redis:/data
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_openvpn:
        image: alpine
        volumes:
            - ./mod_openvpn:/opt/openvpn
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure

volumes:
        mod_manager:
        mod_report:
        mod_slips:
        mod_openvpn:
        mod_redis:
        mod_comm_send:
        mod_comm_recv:
