version: '3.1'

services:
    mod_manager:
        image: python:slim
        volumes:
            - mod_manager:/opt/manager
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_comm_recv:
        image: python:slim
        volumes:
            - mod_comm_send:/opt/mod_comm_recv
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_comm_send:
        image: python:slim
        volumes:
            - mod_comm_send:/opt/mod_comm_send
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_report:
        image: alpine
        volumes:
            - mod_report:/opt/report
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_slips:
        image: alpine
        volumes:
            - mod_slips:/opt/dataset
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_redis:
        image: redis
        volumes:
            - mod_redis:/data
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_openvpn:
        image: alpine
        volumes:
            - mod_openvpn:/opt/openvpn
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure

volumes:
        mod_manager:
        mod_report:
        mod_slips:
        mod_openvpn:
        mod_redis:
        mod_comm_send:
        mod_comm_recv:
