version: '3.1'

services:
    mod_manager:
        image: alpine
        volumes:
            - mod_manager:/opt/manager
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_email:
        image: alpine
        volumes:
            - mod_email:/opt/mod_email
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_report:
        image: alpine
        volumes:
            - mod_report:/opt/report
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_slips:
        image: alpine
        volumes:
            - mod_slips:/opt/dataset
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_redis:
        image: alpine
        volumes:
            - mod_redis:/opt/redis
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
    mod_openvpn:
        image: alpine
        volumes:
            - mod_openvpn:/opt/openvpn
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure

volumes:
        mod_manager:
        mod_email:
        mod_report:
        mod_slips:
        mod_redis:
        mod_openvpn:
